apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamforge.fullname" . }}-secret
  labels:
    {{- include "streamforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  POSTGRES_DSN: {{ include "streamforge.postgresDSN" . | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDatabase | quote }}
